name: GitHub MCP server
version: 0.0.1
schema: v1

mcpServers:
  - name: github
    command: npx.cmd
    args:
      - "-y"
      - "@modelcontextprotocol/server-github@latest"
    env:
      GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"

models:
  - name: Mistral
    provider: ollama
    model: mistral

  - name: DeepSeek
    provider: ollama
    model: deepseek-coder:6.7b

  - name: CodeLlama
    provider: ollama
    model: codellama:7b

  - name: Claude 3.5 Sonnet
    provider: anthropic
    apiBase: https://api.anthropic.com/v1
    model: claude-3-5-sonnet-20250108
    apiKey: "${{secrets.ANTHROPIC_API_KEY}}"

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
